FROM node:buster AS builder
COPY . /code
WORKDIR /code/packages/sygna-gateway
RUN export PROTOC_ZIP=protoc-3.7.1-linux-x86_64.zip && \
  curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.7.1/$PROTOC_ZIP && \
  unzip -o $PROTOC_ZIP -d /usr/local bin/protoc && \
  unzip -o $PROTOC_ZIP -d /usr/local 'include/*' && \
  npm install && \
  bash ./gen_proto.sh && \
  npm run build && \
  rm -rf node_modules

FROM node:alpine
COPY --from=builder /code/packages/sygna-gateway /code
WORKDIR /code
RUN mkdir -p /etc/sygna-gateway && npm install --production
CMD ["node", "/code/dist/index.js", "/etc/sygna-gateway/config.json"]